In [ ]:
import pickle as pkl
from transformer_raw.modules import encoder, decoder
def load(path : str) -> None:
	pickle_encoder = open(f'{path}/encoder.pkl', 'rb')
	pickle_decoder = open(f'{path}/decoder.pkl', 'rb')
	# print(type(self.encoder.dropout.scale))

	encoder = pkl.load(pickle_encoder)
	decoder = pkl.load(pickle_decoder)
	pickle_encoder.close()
	pickle_decoder.close()
	return encoder, decoder


In [2]:
path = "./saved_models/seq2seq_model/10"
encoder, decoder = load(path)


In [3]:
import cupy as np
a = np.random.rand(5, 10, 20)
b = np.random.rand(20, 30)
c = np.random.rand(10, 30)


In [4]:
from transformer.utils import Utils
import tenseal as ts
utils = Utils("./keys", has_secret_key=True)


In [5]:
a_ = utils.encrypt_matrix(a)
b_ = utils.encrypt_matrix(b)
c_ = utils.encrypt_matrix(c)


In [11]:
aa = a_.reshape([1,5,10,20])
aa = aa[0].reshape([5,10,20])


In [ ]:
res = Utils.dot(a_, b_)

In [48]:
from typing import Tuple
def transpose_manual(X : ts.CKKSTensor, axes : Tuple[int]) -> ts.CKKSTensor:
	dim = len(axes)
	shape_old = X.shape
	shape_new = [shape_old[ax] for ax in axes]
	X_array = np.empty(shape_old)
	# def set_value(idx, value):
	# 	if len(idx) == 1:
	# 		X_array[idx[0]] = value
	# 	else:
	# 		set_value(idx[1:], value)
	def iterate(arr, idx, dim):
		if dim == len(shape_old):
			for j in range(shape_old[-1]):
				element = np.array([arr[j]])
				print(element.shape)
				X_array[tuple(idx + [j])] = element
			return
		else:
			for i in range(shape_old[dim-1]):
				element = arr[i].reshape(arr.shape[1:])
				# print(element)
				iterate(element, idx + [i], dim + 1)
	# print(shape_old)

	iterate(X, [], 1)
	print(X_array)

a = np.arange(3*4*5).reshape((3, 4, 5))
transpose_manual(a, (1, 0, 2))

(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
(1,)
[[[ 0.  1.  2.  3.  4.]
  [ 5.  6.  7.  8.  9.]
  [10. 11. 12. 13. 14.]
  [15. 16. 17. 18. 19.]]

 [[20. 21. 22. 23. 24.]
  [25. 26. 27. 28. 29.]
  [30. 31. 32. 33. 34.]
  [35. 36. 37. 38. 39.]]

 [[40. 41. 42. 43. 44.]
  [45. 46. 47. 48. 49.]
  [50. 51. 52. 53. 54.]
  [55. 56. 57. 58. 59.]]]
